version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running tests
      - pytest tests/
  build:
    commands:
      - echo Build started on `date`
      - echo Building the web application
      - python build.py
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Zipping the build directory
      - zip -r build.zip build/ # Komprimiere das build-Verzeichnis in ein Zip-Archiv

artifacts:
  files:
    - build.zip # Stelle sicher, dass das Zip-Archiv als Artefakt aufgeführt wird

